/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseMain: typeof import('./components/layouts/BaseMain.vue')['default']
    BottomPanel: typeof import('./components/BottomPanel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElWatermark: typeof import('element-plus/es')['ElWatermark']
    GeoJSONParser: typeof import('./components/parser/GeoJSONParser.vue')['default']
    GeoStrEditor: typeof import('./components/editor/GeoStrEditor.vue')['default']
    GisTextParser: typeof import('./components/parser/GisTextParser.vue')['default']
    LeftPanel: typeof import('./components/LeftPanel.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    MainMap: typeof import('./components/MainMap.vue')['default']
    OlMapBase: typeof import('./components/gismap/olMapBase.vue')['default']
    WktParser: typeof import('./components/parser/WktParser.vue')['default']
  }
}
